#!/bin/bash

# Setup script for local development environment
echo "🔧 Setting up local development environment..."

# Navigate to faculty-pulse-app directory
cd "$(dirname "$0")"

# Check if .env file exists
if [ ! -f .env ]; then
    echo "📝 Creating .env file from .env.example..."
    cp .env.example .env
    
    # Enable dev mode
    echo "" >> .env
    echo "# Local development mode (auto-generated by setup script)" >> .env
    echo "VITE_DEV_MODE=true" >> .env
    
    echo "✅ .env file created with dev mode enabled"
else
    echo "⚠️  .env file already exists"
    
    # Check if VITE_DEV_MODE is set
    if grep -q "VITE_DEV_MODE" .env; then
        echo "ℹ️  VITE_DEV_MODE already configured"
    else
        echo "📝 Adding VITE_DEV_MODE to existing .env file..."
        echo "" >> .env
        echo "# Local development mode" >> .env
        echo "VITE_DEV_MODE=true" >> .env
        echo "✅ VITE_DEV_MODE added to .env"
    fi
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "🚀 To start the development server, run:"
echo "   npm run dev"
echo ""
echo "📋 Dev mode features:"
echo "   • No login required"
echo "   • All premium features unlocked"
echo "   • Auto-generator available"
echo "   • No ads"
echo ""
